//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use std::str::FromStr;

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(Some(1))")]
#[serde(rename_all = "lowercase")]
/// The todo status
pub enum Status {
    /// Completed todo
    #[sea_orm(string_value = "completed")]
    Completed,
    /// Pending todo
    #[sea_orm(string_value = "pending")]
    Pending,
    /// Progress todo
    #[sea_orm(string_value = "progress")]
    Progress,
    /// Cancelled todo
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}

impl Status {
    /// Convert the status to string
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Completed => "completed",
            Self::Pending => "pending",
            Self::Progress => "progress",
            Self::Cancelled => "cancelled",
        }
    }
}

impl FromStr for Status {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().trim() {
            "completed" => Ok(Self::Completed),
            "pending" => Ok(Self::Pending),
            "progress" => Ok(Self::Progress),
            "cancelled" => Ok(Self::Cancelled),
            _ => Err(format!("The status `{s}` is invalid, expected `completed`, `pending`, `progress` or `cancelled`")),
        }
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "todo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique_key)]
    pub uuid: Uuid,
    pub user_id: u32,
    pub title: String,
    pub status: Status,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
